siteTitle="TransTraks Documentation"
baseColor = "#884499"
linkPrefix = "/tt-docs"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
  "/docs/accident/"
]
